apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - geo-deployment.yaml
  - routing-deployment.yaml
  - audit-deployment.yaml

images:
  - name: geo-service
    newTag: latest
  - name: routing-service
    newTag: latest
  - name: audit-service
    newTag: latest