apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-service
  namespace: gps-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routing-service
  template:
    metadata:
      labels:
        app: routing-service
    spec:
      containers:
        - name: routing-service
          image: simon-routing-service:latest
          envFrom:
            - configMapRef:
                name: global-config
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: routing-service
  namespace: gps-services
spec:
  selector:
    app: routing-service
  type: NodePort    
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 30002
